clean db
tgifmike/newblog pull request #12
Opened 2023-06-26 20:18 UTC by tgifmike

some styling from before we made it where it needs approval
removed old env
creadted new .env.example
put local creds
ignored .env.example

2023-07-20 13:13 UTC, dstotz requested changes

2023-07-20 13:13 UTC, dstotz commented on .gitignore
> +.env.example
example env file is ignored rather than allowed. Change to `!.env.example` and then commit example file

2023-07-20 13:20 UTC, tgifmike commented on .gitignore
> +.env.example
done and commited

2023-07-24 19:17 UTC, dstotz approved these changes

2023-07-24 19:19 UTC, merged